import { Injectable, signal } from '@angular/core';

type Language = 'en' | 'ar';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'search...': 'Search...', selected: 'selected', 'no data found': 'No data found', showing: 'Showing', to: 'to', of: 'of', previous: 'Previous', next: 'Next', clear: 'Clear', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete', close: 'Close', review: 'Review', yes: 'Yes', no: 'No', 'total reviews': 'Total reviews', 'expand sidebar': 'Expand sidebar', 'collapse sidebar': 'Collapse sidebar',
    image: 'Image', name: 'Name', category: 'Category', stock: 'Stock', rating: 'Rating', featured: 'Featured', status: 'Status', payment: 'Payment', date: 'Date', customer: 'Customer', total: 'Total', actions: 'Actions', description: 'Description', title: 'Title', email: 'Email', phone: 'Phone', address: 'Address', active: 'Active', inactive: 'Inactive', edit: 'Edit', view: 'View', save: 'Save', update: 'Update', add: 'Add', create: 'Create', search: 'Search', filter: 'Filter', loading: 'Loading...', 'no results': 'No results', icon: 'Icon', color: 'Color', key: 'Key', subtitle: 'Subtitle', updated: 'Updated', code: 'Code', type: 'Type', value: 'Value', used: 'Used', 'max uses': 'Max Uses', expires: 'Expires', entity: 'Entity', action: 'Action', details: 'Details', user: 'User', comment: 'Comment', role: 'Role', permissions: 'Permissions', default: 'Default', changes: 'Changes', percent: 'Percent', fixed: 'Fixed', unlimited: 'Unlimited',
    about: 'About', contact: 'Contact', 'contact details': 'Contact details', 'business hours': 'Business hours', whatsapp: 'WhatsApp', 'about text': 'About text', 'footer & contact': 'Footer & Contact', 'about page': 'About page', 'footer about': 'Footer about (short blurb)', 'contact details shown on the contact page and footer.': 'Contact details shown on the contact page and footer.', 'about text shown on the about page.': 'About text shown on the about page.', 'tell your story...': 'Tell your story...', 'seo & brand': 'SEO & Brand', footer: 'Footer', 'footer categories': 'Footer categories', 'short blurb and category links shown in your store footer.': 'Short blurb and category links shown in your store footer.', 'no categories available': 'No categories available', faq: 'FAQ', 'terms & conditions': 'Terms & Conditions', 'frequently asked questions shown on the faq page.': 'Frequently asked questions shown on the FAQ page.', 'terms & conditions shown on the terms page.': 'Terms & Conditions shown on the terms page.', 'write each question on its own line, followed by the answer.': 'Write each question on its own line, followed by the answer.', 'q: ...': 'Q: ...', 'these terms & conditions govern...': 'These Terms & Conditions govern...', 'export csv': 'Export CSV', 'import csv': 'Import CSV', 'est. restock cost': 'Est. restock cost', 'all products': 'All Products', 'products running low on inventory.': 'Products running low on inventory.', 'no products to export': 'No products to export', 'csv has no data rows': 'CSV has no data rows', 'invoice / pdf': 'Invoice / PDF', refunds: 'Refunds', refund: 'Refund', remaining: 'Remaining', 'refund amount': 'Refund amount', 'order notes': 'Order Notes', 'add a note...': 'Add a note...', 'no notes yet': 'No notes yet', 'note added': 'Note added', 'could not add note': 'Could not add note', 'refund applied': 'Refund applied', 'could not apply refund': 'Could not apply refund', 'enter a valid refund amount': 'Enter a valid refund amount', 'refund exceeds the remaining total': 'Refund exceeds the remaining total',
    products: 'Products', categories: 'Categories', orders: 'Orders', coupons: 'Coupons', users: 'Users', reviews: 'Reviews', roles: 'Roles',
    'add product': 'Add Product', 'delete products': 'Delete Products', 'add category': 'Add Category', 'add coupon': 'Add Coupon', 'add role': 'Add Role',
    'delete categories': 'Delete Categories', 'delete orders': 'Delete Orders', 'delete coupons': 'Delete Coupons', 'delete users': 'Delete Users', 'delete reviews': 'Delete Reviews', 'delete role': 'Delete Role',
    'are you sure?': 'Are you sure?', 'are you sure you want to delete this role? this action cannot be undone.': 'Are you sure you want to delete this role? This action cannot be undone.',
    'all entities': 'All Entities', 'no audit logs found': 'No audit logs found', 'no roles found': 'No roles found',
    'page': 'Page', 'all activity': 'All Activity', 'profile changes': 'Profile Changes',
    'no changes': 'No changes', 'review the actions performed from your account.': 'Review the actions performed from your account.',
    'filter and search your recent actions.': 'Filter and search your recent actions.',
    'switch to light mode': 'Switch to light mode', 'switch to dark mode': 'Switch to dark mode',
    revenue: 'Revenue', pending: 'Pending', 'low stock': 'Low Stock', 'orders awaiting processing': 'orders awaiting processing', 'items with ≤10 stock': 'items with ≤10 stock', overview: 'Overview', dashboard: 'Dashboard', 'live store metrics': 'Live store metrics', 'at a glance': 'At a glance', 'key metrics': 'Key metrics', 'store performance': 'Store performance', performance: 'Performance', 'track your store activity over time.': 'Track your store activity over time.', 'recent orders': 'Recent Orders', 'no orders yet': 'No orders yet', 'activity history': 'Activity history', 'two-factor authentication': 'Two-Factor Authentication', 'forgot password?': 'Forgot Password?', 'reset password': 'Reset Password', 'verify your email': 'Verify Your Email',
    admin: 'Admin', 'admin workspace': 'Admin workspace', administrator: 'Administrator',
    logout: 'Log out', 'switch to arabic': 'Switch to Arabic', 'switch to english': 'Switch to English',
    commerce: 'Commerce', people: 'People',
    account: 'Account', 'my activity': 'My Activity', system: 'System', 'audit logs': 'Audit Logs', settings: 'Settings',
    'order id': 'Order ID', 'all status': 'All Status', processed: 'Processed', shipped: 'Shipped',
    delivered: 'Delivered', cancelled: 'Cancelled', 'order info': 'Order Info', 'save status': 'Save status', saving: 'Saving...',
    'shipping details': 'Shipping', city: 'City', country: 'Country', carrier: 'Carrier',
    'tracking number': 'Tracking number', 'open tracking link': 'Open tracking link', 'save shipment': 'Save shipment', items: 'Items',
    product: 'Product', qty: 'Qty', price: 'Price', 'admin profile': 'Admin Profile', 'update account details': 'Update your account details and password.',
    'new password': 'New password', 'keep current password': 'Leave blank to keep current password', 'save profile': 'Save profile',
    'profile saved': 'Profile saved', 'shipping settings': 'Shipping Settings', 'shipping description': 'Set the warehouse location and price per kilometre used at checkout.',
    'distance pricing': 'Distance pricing', 'warehouse latitude': 'Warehouse latitude', 'warehouse longitude': 'Warehouse longitude',
    'price per kilometre': 'Price per kilometre', 'base rate fallback': 'Base rate fallback', 'free shipping threshold': 'Free shipping threshold',
    'fallback location rates': 'Fallback location rates', 'fallback description': 'Used when checkout does not provide coordinates.', 'add rate': 'Add rate',
    label: 'Label', rate: 'Rate', remove: 'Remove', 'save shipping': 'Save shipping', 'shipping saved': 'Shipping settings saved',
    'revenue over time': 'Revenue Over Time', 'products by category': 'Products by Category', 'orders by status': 'Orders by Status', 'orders over time': 'Orders Over Time',
    period: 'Period', day: 'Day', week: 'Week', month: 'Month', 'user growth': 'User Growth', 'new users': 'New Users', 'top products': 'Top Products', 'units sold': 'Units Sold',
    '2fa is enabled': '2FA is enabled', '2fa is not enabled': '2FA is not enabled',
    'enter the 6-digit code from your authenticator app to disable 2fa.': 'Enter the 6-digit code from your authenticator app to disable 2FA.',
    'enter 6-digit code': 'Enter 6-digit code', 'disable 2fa': 'Disable 2FA',
    'scan this qr code with your authenticator app:': 'Scan this QR code with your authenticator app:', 'qr code': 'QR Code',
    'or enter this secret manually:': 'Or enter this secret manually:', 'enter 6-digit code to verify': 'Enter 6-digit code to verify',
    'verify & enable': 'Verify & Enable', 'setup 2fa': 'Setup 2FA',
    '2fa enabled successfully': '2FA enabled successfully', '2fa disabled successfully': '2FA disabled successfully', 'invalid token': 'Invalid token',
    'profile picture': 'Profile picture', 'uploading picture...': 'Uploading picture...', 'use a square image for the best result.': 'Use a square image for the best result.',
    'could not save profile': 'Could not save profile',
    'no file selected.': 'No file selected.', 'you can upload up to 10 images at a time.': 'You can upload up to 10 images at a time.',
    'only image files can be uploaded.': 'Only image files can be uploaded.', 'images must be 5mb or smaller.': 'Images must be 5MB or smaller.',
    'photo uploaded': 'Photo uploaded', 'image uploaded': 'Image uploaded', 'images uploaded': 'Images uploaded',
    'the server did not return an image url.': 'The server did not return an image url.', 'the server did not return any images.': 'The server did not return any images.',
    'please choose a .csv file.': 'Please choose a .csv file.', 'csv must be 2mb or smaller.': 'CSV must be 2MB or smaller.', 'could not read that file.': 'Could not read that file.',
    'could not save shipping settings': 'Could not save shipping settings', 'tracking url': 'Tracking URL',
    'site settings saved': 'Site settings saved', 'could not save site settings': 'Could not save site settings',
    'site & seo settings': 'Site & SEO Settings', 'control the storefront title, search metadata, and brand assets.': 'Control the storefront title, search metadata, and brand assets.',
    'search engine metadata': 'Search engine metadata', 'these values describe your store in search results and browser tabs.': 'These values describe your store in search results and browser tabs.',
    'site title': 'Site title', 'meta description': 'Meta description', keywords: 'Keywords',
    'separate keywords with commas.': 'Separate keywords with commas.', 'canonical url': 'Canonical URL',
    'brand assets': 'Brand assets', 'use public image urls for your logo, browser icon, and social previews.': 'Use public image URLs for your logo, browser icon, and social previews.',
    'logo url': 'Logo URL', 'favicon url': 'Favicon URL', 'social preview image url': 'Social preview image URL',
    'logo preview': 'Logo preview', 'site logo preview': 'Site logo preview', characters: 'characters',
    'save site settings': 'Save site settings', 'open navigation menu': 'Open navigation menu', 'open profile': 'Open profile', 'close navigation menu': 'Close navigation menu',
    'email address': 'Email Address', 'phone number': 'Phone number', 'coupon code': 'Coupon code', 'select type': 'Select type', 'select country': 'Select country', password: 'Password', 'enter your password': 'Enter your password', 'keep me logged in': 'Keep me logged in',
    'signing in...': 'Signing in...', 'sign in': 'Sign In', 'enter your email to receive a reset link': 'Enter your email to receive a reset link',
    'sending...': 'Sending...', 'send reset link': 'Send Reset Link', 'back to login': 'Back to Login',
    'check your email for the reset link.': 'Check your email for the reset link.',
    'enter your new password': 'Enter your new password', 'enter new password': 'Enter new password', 'confirm password': 'Confirm Password',
    'confirm new password': 'Confirm new password', 'resetting...': 'Resetting...',
    'passwords do not match': 'Passwords do not match', 'password updated successfully! redirecting to login...': 'Password updated successfully! Redirecting to login...',
    "we've sent a 6-digit code to your email": "We've sent a 6-digit code to your email", 'verification code': 'Verification Code',
    'verifying...': 'Verifying...', 'resend in ': 'Resend in ', 'resend code': 'Resend code',
    'email verified successfully! redirecting...': 'Email verified successfully! Redirecting...',
    'rich description (html)': 'Rich Description (HTML)', 'category id': 'Category ID', 'select category': 'Select category', brand: 'Brand', 'gallery images': 'Gallery Images',
    'write a short description...': 'Write a short description...', 'write detailed product description...': 'Write detailed product description...',
    'uploading image...': 'Uploading image...', 'uploading gallery...': 'Uploading gallery...',
    'product image': 'Product image', 'gallery image': 'Gallery image',
    '← back to products': '← Back to products', 'product details': 'Product details', 'edit product': 'Edit product',
    'no product image': 'No product image', 'in stock': 'In stock', 'out of stock': 'Out of stock',
    'featured product': 'Featured product', 'no description available.': 'No description available.',
    'rich description': 'Rich description', 'loading product...': 'Loading product...',
    'enter the video embed url': 'Enter the video embed URL',
    '← back to categories': '← Back to categories', 'update catalog item': 'Update catalog item', 'add to catalog': 'Add to catalog', 'edit category': 'Edit category', 'new category': 'New category', 'save category': 'Save category',
    'category content': 'Category content', 'write a category description...': 'Write a category description...', 'write detailed category content...': 'Write detailed category content...',
    'category information': 'Category information', 'category image': 'Category image', 'used as the background of this category on the store.': 'Used as the background of this category on the store.',
    'category details': 'Category details', 'no category image': 'No category image', 'loading category...': 'Loading category...',
    'role information': 'Role Information', 'role name': 'Role Name', 'default role': 'Default Role', 'automatically assigned to new users': 'Automatically assigned to new users',
    'e.g. editor, manager': 'e.g. Editor, Manager', 'permissions selected': 'permissions selected', 'select all': 'Select All', 'save role': 'Save Role',
    read: 'Read', manage: 'Manage',
    '← back': '← Back', none: 'None',
    'email:': 'Email:', 'phone:': 'Phone:', 'admin:': 'Admin:', 'role:': 'Role:', 'address:': 'Address:',
    'customer:': 'Customer:', 'city:': 'City:', 'country:': 'Country:', 'carrier:': 'Carrier:', 'tracking number:': 'Tracking number:',
    shipping: 'Shipping', coupon: 'Coupon', 'max uses (0=unlimited)': 'Max Uses (0=unlimited)', 'valid from': 'Valid From', 'valid until': 'Valid Until',
    '← back to orders': '← Back to Orders',
    'only admin accounts are allowed to sign in here.': 'Only admin accounts are allowed to sign in here.',
    catalog: 'Catalog', sales: 'Sales', team: 'Team', 'team member': 'Team member', access: 'Access', security: 'Security', cms: 'CMS', feedback: 'Feedback', marketing: 'Marketing',
    order: 'Order', 'order details': 'Order details',
    'manage your product catalog.': 'Manage your product catalog.', 'track and manage customer orders.': 'Track and manage customer orders.',
    'manage team members and permissions.': 'Manage team members and permissions.', 'manage access roles and permissions.': 'Manage access roles and permissions.',
    'organize products into categories.': 'Organize products into categories.', 'review system activity and changes.': 'Review system activity and changes.',
    'monitor customer feedback.': 'Monitor customer feedback.',
    'manage discounts and promotions.': 'Manage discounts and promotions.',
    // Buttons / headers / form actions (kept in sync with app-page-header + app-form-actions usage)
    all: 'All', 'clear filters': 'Clear filters', 'saving...': 'Saving...', 'update status': 'Update Status',
    'shipment tracking': 'Shipment Tracking', 'customer since': 'Customer Since',
    'customer details': 'Customer Details', 'order items': 'Order Items', 'order summary': 'Order Summary', 'shipping address': 'Shipping Address',
    subtotal: 'Subtotal', 'items count': 'Items Count', 'order date': 'Order Date', 'payment status': 'Payment Status',
    'no items in this order': 'No items in this order', 'loading order details...': 'Loading order details...',
    'this field is required': 'This field is required',
    'edit user': 'Edit user', 'new user': 'New user', 'update account': 'Update account', 'add to team': 'Add to team', 'save user': 'Save user',
    'add user': 'Add User', 'user details': 'User details',
    'new product': 'New product', 'save product': 'Save product',
    'edit coupon': 'Edit coupon', 'create coupon': 'Create coupon', 'update coupon': 'Update coupon', 'new coupon': 'New coupon', 'save coupon': 'Save coupon',
    'coupon details': 'Coupon details',
    'edit role': 'Edit role', 'new role': 'New role', 'update role': 'Update role',
    '← back to users': '← Back to users', '← back to roles': '← Back to roles', '← back to coupons': '← Back to coupons',
    verify: 'Verify', 'shipping settings saved': 'Shipping settings saved',
    paid: 'Paid', unpaid: 'Unpaid', refunded: 'Refunded', failed: 'Failed',
    'back to products': 'Back to products', 'back to categories': 'Back to categories', 'back to users': 'Back to users',
    'back to orders': 'Back to orders', 'back to coupons': 'Back to coupons', 'back to roles': 'Back to roles',
    'role details': 'Role details',
    'select photo': 'Select photo', 'select photos': 'Select photos',
    'save changes': 'Save changes', 'do you want to save your changes?': 'Do you want to save your changes?',
    'added on': 'Added on', 'added by': 'Added by',
    'upload image': 'Upload image', 'do you want to upload this image?': 'Do you want to upload this image?',
    'delete image': 'Delete image', 'do you want to delete this image?': 'Do you want to delete this image?',
    'deleted successfully': 'Deleted successfully',
    'saved successfully': 'Saved successfully',
    'this order is in a final state and cannot be changed.': 'This order is in a final state and cannot be changed.',
    'order updated': 'Order updated', 'could not save order': 'Could not save order',
    'no changes to save': 'No changes to save',
    'you cannot delete your own account': 'You cannot delete your own account',
    payments: 'Payments', 'payment methods': 'Payment Methods', 'add payment method': 'Add Payment Method',
    'edit payment method': 'Edit payment method', 'new payment method': 'New payment method', 'save payment method': 'Save payment method',
    'delete payment methods': 'Delete Payment Methods', 'selected payment methods?': 'selected payment methods?',
    'payment method details': 'Payment method details', appearance: 'Appearance',
    'available payment gateways your countries can offer at checkout.': 'Available payment gateways your countries can offer at checkout.',
    'a unique machine key the storefront uses (e.g. cod, paymob, fawry, mada, tabby).': 'A unique machine key the storefront uses (e.g. cod, paymob, fawry, mada, tabby).',
    'could not save payment method': 'Could not save payment method',
    transactions: 'Transactions', 'every payment attempt recorded from the storefront, across all countries.': 'Every payment attempt recorded from the storefront, across all countries.',
    reference: 'Reference', method: 'Method', amount: 'Amount', methods: ' methods',
    countries: 'Countries', 'add country': 'Add Country', 'edit country': 'Edit country', 'new country': 'New country',
    'save country': 'Save country', 'delete countries': 'Delete Countries', 'selected countries?': 'selected countries?',
    'country code': 'Country code', 'phone code': 'Phone code', flag: 'Flag', 'select a currency': 'Select a currency',
    'country information': 'Country information', 'the currency customers are charged in for this country.': 'The currency customers are charged in for this country.',
    'select the payment methods available to customers in this country.': 'Select the payment methods available to customers in this country.',
    'no payment methods yet': 'No payment methods yet', 'add payment methods': 'Add payment methods',
    'each country has its own currency and the payment methods available to its customers.': 'Each country has its own currency and the payment methods available to its customers.',
    'could not save country': 'Could not save country',
    currencies: 'Currencies', 'add currency': 'Add Currency', 'edit currency': 'Edit currency', 'new currency': 'New currency',
    'save currency': 'Save currency', 'delete currencies': 'Delete Currencies', 'selected currencies?': 'selected currencies?',
    currency: 'Currency', symbol: 'Symbol', base: 'Base', 'base currency': 'Base currency', 'currency details': 'Currency details',
    'rate = how many of this currency equal 1 of your base currency.': 'Rate = how many of this currency equal 1 of your base currency.',
    'currencies used by your countries, with the exchange rate against your base currency.': 'Currencies used by your countries, with the exchange rate against your base currency.',
    'could not save currency': 'Could not save currency',
    'checkout & payments': 'Checkout & payments', 'enable cash on delivery': 'Enable Cash on Delivery', 'default currency': 'Default currency',
    'country-based payments': 'Country-based payments', 'global payment defaults. country-specific payment methods are set per country.': 'Global payment defaults. Country-specific payment methods are set per country.',
    'manage which payment methods are available in each country, and the currency used there.': 'Manage which payment methods are available in each country, and the currency used there.',
    'You are offline. Check your connection and try again.': 'You are offline. Check your connection and try again.',
    'The server is temporarily unreachable. Please try again.': 'The server is temporarily unreachable. Please try again.',
    'You are offline. Some features will not work until you reconnect.': 'You are offline. Some features will not work until you reconnect.',
    'The server is temporarily unreachable. We will keep trying.': 'The server is temporarily unreachable. We will keep trying.',
  },
  ar: {
    'search...': 'بحث...', selected: 'محدد', 'no data found': 'لا توجد بيانات', showing: 'عرض', to: 'إلى', of: 'من', previous: 'السابق', next: 'التالي', clear: 'مسح', cancel: 'إلغاء', confirm: 'تأكيد', delete: 'حذف', close: 'إغلاق', review: 'مراجعة', yes: 'نعم', no: 'لا', 'total reviews': 'إجمالي التقييمات', 'expand sidebar': 'توسيع القائمة الجانبية', 'collapse sidebar': 'طي القائمة الجانبية',
    image: 'الصورة', name: 'الاسم', category: 'التصنيف', stock: 'المخزون', rating: 'التقييم', featured: 'مميز', status: 'الحالة', payment: 'الدفع', date: 'التاريخ', customer: 'العميل', total: 'الإجمالي', actions: 'الإجراءات', description: 'الوصف', title: 'العنوان', email: 'البريد الإلكتروني', phone: 'الهاتف', address: 'العنوان', active: 'نشط', inactive: 'غير نشط', edit: 'تعديل', view: 'عرض', save: 'حفظ', update: 'تحديث', add: 'إضافة', create: 'إنشاء', search: 'بحث', filter: 'تصفية', loading: 'جارٍ التحميل...', 'no results': 'لا توجد نتائج', icon: 'الأيقونة', color: 'اللون', key: 'المفتاح', subtitle: 'العنوان الفرعي', updated: 'آخر تحديث', code: 'الرمز', type: 'النوع', value: 'القيمة', used: 'المستخدم', 'max uses': 'الحد الأقصى للاستخدام', expires: 'ينتهي', entity: 'العنصر', action: 'الإجراء', details: 'التفاصيل', user: 'المستخدم', comment: 'التعليق', role: 'الدور', permissions: 'الصلاحيات', default: 'افتراضي', changes: 'التغييرات', percent: 'نسبة مئوية', fixed: 'ثابت', unlimited: 'غير محدود',
    about: 'من نحن', contact: 'تواصل معنا', 'contact details': 'بيانات التواصل', 'business hours': 'ساعات العمل', whatsapp: 'واتساب', 'about text': 'نص من نحن', 'footer & contact': 'التذييل والتواصل', 'about page': 'صفحة من نحن', 'footer about': 'نبذة قصيرة في التذييل', 'contact details shown on the contact page and footer.': 'بيانات التواصل المعروضة في صفحة التواصل والتذييل.', 'about text shown on the about page.': 'نص النبذة المعروض في صفحة من نحن.', 'tell your story...': 'احكِ قصتك...', 'seo & brand': 'السّيو والعلامة التجارية', footer: 'التذييل', 'footer categories': 'تصنيفات التذييل', 'short blurb and category links shown in your store footer.': 'نبذة قصيرة وروابط التصنيفات المعروضة في تذييل متجرك.', 'no categories available': 'لا توجد تصنيفات', faq: 'الأسئلة الشائعة', 'terms & conditions': 'الشروط والأحكام', 'frequently asked questions shown on the faq page.': 'الأسئلة الشائعة المعروضة في صفحة الأسئلة الشائعة.', 'terms & conditions shown on the terms page.': 'الشروط والأحكام المعروضة في صفحة الشروط.', 'write each question on its own line, followed by the answer.': 'اكتب كل سؤال في سطر مستقل متبوعاً بالإجابة.', 'q: ...': 'س: ...', 'these terms & conditions govern...': 'تحدد هذه الشروط والأحكام...', 'export csv': 'تصدير CSV', 'import csv': 'استيراد CSV', 'est. restock cost': 'التكلفة التقديرية لإعادة التخزين', 'all products': 'كل المنتجات', 'products running low on inventory.': 'المنتجات التي أوشك مخزونها على النفاد.', 'no products to export': 'لا توجد منتجات للتصدير', 'csv has no data rows': 'لا توجد صفوف بيانات في ملف CSV', 'invoice / pdf': 'فاتورة / PDF', refunds: 'المبالغ المستردة', refund: 'استرداد', remaining: 'المتبقي', 'refund amount': 'مبلغ الاسترداد', 'order notes': 'ملاحظات الطلب', 'add a note...': 'أضف ملاحظة...', 'no notes yet': 'لا توجد ملاحظات بعد', 'note added': 'تمت إضافة الملاحظة', 'could not add note': 'تعذر إضافة الملاحظة', 'refund applied': 'تم تطبيق الاسترداد', 'could not apply refund': 'تعذر تطبيق الاسترداد', 'enter a valid refund amount': 'أدخل مبلغ استرداد صحيحاً', 'refund exceeds the remaining total': 'الاسترداد يتجاوز المبلغ المتبقي',
    products: 'المنتجات', categories: 'التصنيفات', orders: 'الطلبات', coupons: 'الكوبونات', users: 'المستخدمون', reviews: 'التقييمات', roles: 'الأدوار',
    'add product': 'إضافة منتج', 'delete products': 'حذف المنتجات', 'add category': 'إضافة تصنيف', 'add coupon': 'إضافة كوبون', 'add role': 'إضافة دور',
    'delete categories': 'حذف التصنيفات', 'delete orders': 'حذف الطلبات', 'delete coupons': 'حذف الكوبونات', 'delete users': 'حذف المستخدمين', 'delete reviews': 'حذف التقييمات', 'delete role': 'حذف الدور',
    'are you sure?': 'هل أنت متأكد؟', 'are you sure you want to delete this role? this action cannot be undone.': 'هل أنت متأكد من حذف هذا الدور؟ لا يمكن التراجع عن هذا الإجراء.',
    'all entities': 'كل العناصر', 'no audit logs found': 'لا توجد سجلات تدقيق', 'no roles found': 'لا توجد أدوار',
    'page': 'صفحة', 'all activity': 'كل النشاطات', 'profile changes': 'تغييرات الملف الشخصي',
    'no changes': 'لا توجد تغييرات', 'review the actions performed from your account.': 'راجع الإجراءات التي تم تنفيذها من حسابك.',
    'filter and search your recent actions.': 'تصفية وبحث في إجراءاتك الأخيرة.',
    'switch to light mode': 'التبديل إلى الوضع الفاتح', 'switch to dark mode': 'التبديل إلى الوضع الداكن',
    'selected products?': 'منتجات محددة؟', 'selected categories?': 'تصنيفات محددة؟', 'selected orders?': 'طلبات محددة؟',
    'selected coupons?': 'كوبونات محددة؟', 'selected users?': 'مستخدمون محددون؟', 'selected reviews?': 'تقييمات محددة؟',
    revenue: 'الإيرادات', pending: 'قيد الانتظار', 'low stock': 'مخزون منخفض', 'orders awaiting processing': 'طلبات بانتظار المعالجة', 'items with ≤10 stock': 'منتجات مخزونها 10 أو أقل', overview: 'نظرة عامة', dashboard: 'لوحة التحكم', 'live store metrics': 'إحصاءات المتجر المباشرة', 'at a glance': 'نظرة سريعة', 'key metrics': 'المؤشرات الرئيسية', 'store performance': 'أداء المتجر', performance: 'الأداء', 'track your store activity over time.': 'تابع نشاط متجرك عبر الزمن.', 'recent orders': 'أحدث الطلبات', 'no orders yet': 'لا توجد طلبات بعد', 'activity history': 'سجل النشاط', 'two-factor authentication': 'المصادقة الثنائية', 'forgot password?': 'هل نسيت كلمة المرور؟', 'reset password': 'إعادة تعيين كلمة المرور', 'verify your email': 'تحقق من بريدك الإلكتروني',
    admin: 'المسؤول', 'admin workspace': 'مساحة المسؤول', administrator: 'مدير النظام',
    logout: 'تسجيل الخروج', 'switch to arabic': 'التبديل إلى العربية', 'switch to english': 'التبديل إلى الإنجليزية',
    commerce: 'التجارة', people: 'المستخدمون',
    account: 'الحساب', 'my activity': 'نشاطي', system: 'النظام', 'audit logs': 'سجل التدقيق', settings: 'الإعدادات',
    'order id': 'رقم الطلب', 'all status': 'كل الحالات', processed: 'قيد المعالجة', shipped: 'تم الشحن',
    delivered: 'تم التسليم', cancelled: 'ملغى', 'order info': 'بيانات الطلب', 'save status': 'حفظ الحالة', saving: 'جارٍ الحفظ...',
    'shipping details': 'الشحن', city: 'المدينة', country: 'الدولة', carrier: 'شركة الشحن',
    'tracking number': 'رقم التتبع', 'open tracking link': 'فتح رابط التتبع', 'save shipment': 'حفظ بيانات الشحن', items: 'المنتجات',
    product: 'المنتج', qty: 'الكمية', price: 'السعر', 'admin profile': 'ملف المسؤول', 'update account details': 'حدّث بيانات حسابك وكلمة المرور.',
    'new password': 'كلمة المرور الجديدة', 'keep current password': 'اتركه فارغًا للإبقاء على كلمة المرور الحالية', 'save profile': 'حفظ الملف الشخصي',
    'profile saved': 'تم حفظ الملف الشخصي', 'shipping settings': 'إعدادات الشحن', 'shipping description': 'حدد موقع المستودع وسعر الكيلومتر المستخدم عند الدفع.',
    'distance pricing': 'التسعير حسب المسافة', 'warehouse latitude': 'خط عرض المستودع', 'warehouse longitude': 'خط طول المستودع',
    'price per kilometre': 'السعر لكل كيلومتر', 'base rate fallback': 'السعر الأساسي الاحتياطي', 'free shipping threshold': 'حد الشحن المجاني',
    'fallback location rates': 'أسعار المواقع الاحتياطية', 'fallback description': 'تُستخدم عندما لا يرسل الدفع الإحداثيات.', 'add rate': 'إضافة سعر',
    label: 'الاسم', rate: 'السعر', remove: 'حذف', 'save shipping': 'حفظ إعدادات الشحن', 'shipping saved': 'تم حفظ إعدادات الشحن',
    'revenue over time': 'الإيرادات عبر الزمن', 'products by category': 'المنتجات حسب التصنيف', 'orders by status': 'الطلبات حسب الحالة', 'orders over time': 'الطلبات عبر الزمن',
    period: 'الفترة', day: 'يوم', week: 'أسبوع', month: 'شهر', 'user growth': 'نمو المستخدمين', 'new users': 'مستخدمون جدد', 'top products': 'المنتجات الأكثر مبيعاً', 'units sold': 'الوحدات المباعة',
    '2fa is enabled': 'المصادقة الثنائية مفعلة', '2fa is not enabled': 'المصادقة الثنائية غير مفعلة',
    'enter the 6-digit code from your authenticator app to disable 2fa.': 'أدخل الرمز المكون من 6 أرقام من تطبيق المصادقة لإلغاء تفعيل المصادقة الثنائية.',
    'enter 6-digit code': 'أدخل الرمز المكون من 6 أرقام', 'disable 2fa': 'إلغاء تفعيل المصادقة الثنائية',
    'scan this qr code with your authenticator app:': 'امسح رمز QR هذا بتطبيق المصادقة:', 'qr code': 'رمز QR',
    'or enter this secret manually:': 'أو أدخل هذا السر يدوياً:', 'enter 6-digit code to verify': 'أدخل الرمز المكون من 6 أرقام للتحقق',
    'verify & enable': 'تحقق وتفعيل', 'setup 2fa': 'إعداد المصادقة الثنائية',
    '2fa enabled successfully': 'تم تفعيل المصادقة الثنائية بنجاح', '2fa disabled successfully': 'تم إلغاء تفعيل المصادقة الثنائية بنجاح', 'invalid token': 'رمز غير صالح',
    'profile picture': 'صورة الملف الشخصي', 'uploading picture...': 'جارٍ رفع الصورة...', 'use a square image for the best result.': 'استخدم صورة مربعة للحصول على أفضل نتيجة.',
    'could not save profile': 'لم يتم حفظ الملف الشخصي',
    'no file selected.': 'لم يتم اختيار أي ملف.', 'you can upload up to 10 images at a time.': 'يمكنك رفع 10 صور كحد أقصى في المرة الواحدة.',
    'only image files can be uploaded.': 'يمكن رفع ملفات الصور فقط.', 'images must be 5mb or smaller.': 'يجب أن يكون حجم الصورة 5 ميغابايت أو أقل.',
    'photo uploaded': 'تم رفع الصورة', 'image uploaded': 'تم رفع الصورة', 'images uploaded': 'تم رفع الصور',
    'the server did not return an image url.': 'لم يُرجع الخادم رابط الصورة.', 'the server did not return any images.': 'لم يُرجع الخادم أي صور.',
    'please choose a .csv file.': 'يرجى اختيار ملف .csv.', 'csv must be 2mb or smaller.': 'يجب أن يكون حجم ملف CSV 2 ميغابايت أو أقل.', 'could not read that file.': 'تعذّرت قراءة الملف.',
    'could not save shipping settings': 'لم يتم حفظ إعدادات الشحن', 'tracking url': 'رابط التتبع',
    'site settings saved': 'تم حفظ إعدادات الموقع', 'could not save site settings': 'لم يتم حفظ إعدادات الموقع',
    'site & seo settings': 'إعدادات الموقع وتحسين محركات البحث', 'control the storefront title, search metadata, and brand assets.': 'تحكم في عنوان المتجر وبيانات البحث والأصول التعريفية للعلامة التجارية.',
    'search engine metadata': 'بيانات محركات البحث', 'these values describe your store in search results and browser tabs.': 'تصف هذه القيم متجرك في نتائج البحث وعلامات تبويب المتصفح.',
    'site title': 'عنوان الموقع', 'meta description': 'الوصف التعريفي', keywords: 'الكلمات المفتاحية',
    'separate keywords with commas.': 'افصل بين الكلمات المفتاحية بفواصل.', 'canonical url': 'الرابط الأساسي (Canonical)',
    'brand assets': 'الأصول التعريفية للعلامة التجارية', 'use public image urls for your logo, browser icon, and social previews.': 'استخدم روابط صور عامة للشعار وأيقونة المتصفح ومعاينات وسائل التواصل.',
    'logo url': 'رابط الشعار', 'favicon url': 'رابط أيقونة المتصفح', 'social preview image url': 'رابط صورة معاينة وسائل التواصل',
    'logo preview': 'معاينة الشعار', 'site logo preview': 'معاينة شعار الموقع', characters: 'حروف',
    'save site settings': 'حفظ إعدادات الموقع', 'open navigation menu': 'فتح قائمة التنقل', 'open profile': 'فتح الملف الشخصي', 'close navigation menu': 'إغلاق قائمة التنقل',
    'email address': 'البريد الإلكتروني', password: 'كلمة المرور', 'enter your password': 'أدخل كلمة المرور', 'keep me logged in': 'إبقائي مسجلاً الدخول',
    'signing in...': 'جارٍ تسجيل الدخول...', 'sign in': 'تسجيل الدخول', 'enter your email to receive a reset link': 'أدخل بريدك الإلكتروني لاستلام رابط إعادة التعيين',
    'sending...': 'جارٍ الإرسال...', 'send reset link': 'إرسال رابط إعادة التعيين', 'back to login': 'العودة إلى تسجيل الدخول',
    'check your email for the reset link.': 'تحقق من بريدك الإلكتروني لاستلام رابط إعادة التعيين.',
    'enter your new password': 'أدخل كلمة المرور الجديدة', 'enter new password': 'أدخل كلمة المرور الجديدة', 'confirm password': 'تأكيد كلمة المرور',
    'confirm new password': 'تأكيد كلمة المرور الجديدة', 'resetting...': 'جارٍ إعادة التعيين...',
    'passwords do not match': 'كلمتا المرور غير متطابقتين', 'password updated successfully! redirecting to login...': 'تم تحديث كلمة المرور بنجاح! جارٍ إعادة التوجيه إلى تسجيل الدخول...',
    "we've sent a 6-digit code to your email": 'لقد أرسلنا رمزاً من 6 أرقام إلى بريدك الإلكتروني', 'verification code': 'رمز التحقق',
    'verifying...': 'جارٍ التحقق...', 'resend in ': 'إعادة الإرسال خلال ', 'resend code': 'إعادة إرسال الرمز',
    'email verified successfully! redirecting...': 'تم التحقق من البريد الإلكتروني بنجاح! جارٍ إعادة التوجيه...',
    'rich description (html)': 'الوصف الغني (HTML)', 'category id': 'معرف التصنيف', 'select category': 'اختر التصنيف', brand: 'العلامة التجارية', 'phone number': 'رقم الهاتف', 'coupon code': 'رمز الكوبون', 'select type': 'اختر النوع', 'select country': 'اختر الدولة', 'gallery images': 'صور المعرض',
    'write a short description...': 'اكتب وصفاً قصيراً...', 'write detailed product description...': 'اكتب وصفاً تفصيلياً للمنتج...',
    'uploading image...': 'جارٍ رفع الصورة...', 'uploading gallery...': 'جارٍ رفع المعرض...',
    'product image': 'صورة المنتج', 'gallery image': 'صورة المعرض',
    '← back to products': '← العودة إلى المنتجات', 'product details': 'تفاصيل المنتج', 'edit product': 'تعديل المنتج',
    'no product image': 'لا توجد صورة للمنتج', 'in stock': 'متوفر', 'out of stock': 'غير متوفر',
    'featured product': 'منتج مميز', 'no description available.': 'لا يوجد وصف متاح.',
    'rich description': 'الوصف التفصيلي', 'loading product...': 'جارٍ تحميل المنتج...',
    'enter the video embed url': 'أدخل رابط تضمين الفيديو',
    '← back to categories': '← العودة إلى التصنيفات', 'update catalog item': 'تحديث عنصر الكتالوج', 'add to catalog': 'إضافة إلى الكتالوج', 'edit category': 'تعديل التصنيف', 'new category': 'تصنيف جديد', 'save category': 'حفظ التصنيف',
    'category content': 'محتوى التصنيف', 'write a category description...': 'اكتب وصفاً للتصنيف...', 'write detailed category content...': 'اكتب محتوى مفصلاً للتصنيف...',
    'category information': 'بيانات التصنيف', 'category image': 'صورة التصنيف', 'used as the background of this category on the store.': 'تُستخدم كخلفية لهذا التصنيف في المتجر.',
    'category details': 'تفاصيل التصنيف', 'no category image': 'لا توجد صورة للتصنيف', 'loading category...': 'جارٍ تحميل التصنيف...',
    'role information': 'بيانات الدور', 'role name': 'اسم الدور', 'default role': 'الدور الافتراضي', 'automatically assigned to new users': 'يُمنح تلقائياً للمستخدمين الجدد',
    'e.g. editor, manager': 'مثال: محرر، مدير', 'permissions selected': 'صلاحية مختارة', 'select all': 'تحديد الكل', 'save role': 'حفظ الدور',
    read: 'عرض', manage: 'إدارة',
    '← back': '← رجوع', none: 'لا يوجد',
    'email:': 'البريد الإلكتروني:', 'phone:': 'الهاتف:', 'admin:': 'مسؤول:', 'role:': 'الدور:', 'address:': 'العنوان:',
    'customer:': 'العميل:', 'city:': 'المدينة:', 'country:': 'الدولة:', 'carrier:': 'شركة الشحن:', 'tracking number:': 'رقم التتبع:',
    shipping: 'الشحن', coupon: 'كوبون', 'max uses (0=unlimited)': 'الحد الأقصى للاستخدام (0 = غير محدود)', 'valid from': 'صالح من', 'valid until': 'صالح حتى',
    '← back to orders': '← العودة إلى الطلبات',
    'only admin accounts are allowed to sign in here.': 'يُسمح بتسجيل الدخول هنا لحسابات المسؤول فقط.',
    catalog: 'الكتالوج', sales: 'المبيعات', team: 'الفريق', 'team member': 'عضو الفريق', access: 'الوصول', security: 'الأمان', cms: 'المحتوى', feedback: 'التقييمات', marketing: 'التسويق',
    order: 'طلب', 'order details': 'تفاصيل الطلب',
    'manage your product catalog.': 'أدر كتالوج منتجاتك.', 'track and manage customer orders.': 'تتبع طلبات العملاء وأدرها.',
    'manage team members and permissions.': 'أدر أعضاء الفريق والصلاحيات.', 'manage access roles and permissions.': 'أدر أدوار الوصول والصلاحيات.',
    'organize products into categories.': 'نظّم المنتجات في فئات.', 'review system activity and changes.': 'راجع نشاط النظام والتغييرات.',
    'manage cms pages and content.': 'أدر صفحات المحتوى.', 'monitor customer feedback.': 'تابع آراء العملاء.',
    'manage discounts and promotions.': 'أدر الخصومات والعروض.',
    // Buttons / headers / form actions (kept in sync with app-page-header + app-form-actions usage)
    all: 'الكل', 'clear filters': 'مسح التصفية', 'saving...': 'جارٍ الحفظ...', 'update status': 'تحديث الحالة',
    'shipment tracking': 'تتبع الشحنة', 'customer since': 'عميل منذ',
    'customer details': 'بيانات العميل', 'order items': 'منتجات الطلب', 'order summary': 'ملخص الطلب', 'shipping address': 'عنوان الشحن',
    subtotal: 'المجموع الفرعي', 'items count': 'عدد المنتجات', 'order date': 'تاريخ الطلب', 'payment status': 'حالة الدفع',
    'no items in this order': 'لا توجد منتجات في هذا الطلب', 'loading order details...': 'جارٍ تحميل تفاصيل الطلب...',
    'this field is required': 'هذا الحقل مطلوب',
    'edit user': 'تعديل المستخدم', 'new user': 'مستخدم جديد', 'update account': 'تحديث الحساب', 'add to team': 'إضافة إلى الفريق', 'save user': 'حفظ المستخدم',
    'add user': 'إضافة مستخدم', 'user details': 'بيانات المستخدم',
    'new product': 'منتج جديد', 'save product': 'حفظ المنتج',
    'edit coupon': 'تعديل الكوبون', 'create coupon': 'إنشاء كوبون', 'update coupon': 'تحديث الكوبون', 'new coupon': 'كوبون جديد', 'save coupon': 'حفظ الكوبون',
    'coupon details': 'تفاصيل الكوبون',
    'edit role': 'تعديل الدور', 'new role': 'دور جديد', 'update role': 'تحديث الدور',
    '← back to users': '← العودة إلى المستخدمين', '← back to roles': '← العودة إلى الأدوار', '← back to coupons': '← العودة إلى الكوبونات',
    verify: 'تحقق', 'shipping settings saved': 'تم حفظ إعدادات الشحن',
    paid: 'مدفوع', unpaid: 'غير مدفوع', refunded: 'مسترد', failed: 'فشل',
    'back to products': 'العودة إلى المنتجات', 'back to categories': 'العودة إلى التصنيفات', 'back to users': 'العودة إلى المستخدمين',
    'back to orders': 'العودة إلى الطلبات', 'back to coupons': 'العودة إلى الكوبونات', 'back to roles': 'العودة إلى الأدوار',
    'role details': 'تفاصيل الدور',
    'select photo': 'اختر صورة', 'select photos': 'اختر صور',
    'save changes': 'حفظ التغييرات', 'do you want to save your changes?': 'هل تريد حفظ التغييرات؟',
    'added on': 'تاريخ الإضافة', 'added by': 'أضيف بواسطة',
    'upload image': 'رفع صورة', 'do you want to upload this image?': 'هل تريد رفع هذه الصورة؟',
    'delete image': 'حذف صورة', 'do you want to delete this image?': 'هل تريد حذف هذه الصورة؟',
    'deleted successfully': 'تم الحذف بنجاح',
    'saved successfully': 'تم الحفظ بنجاح',
    'this order is in a final state and cannot be changed.': 'هذا الطلب في حالة نهائية ولا يمكن تغييره.',
    'order updated': 'تم تحديث الطلب', 'could not save order': 'تعذر حفظ الطلب',
    'no changes to save': 'لا توجد تغييرات للحفظ',
    'you cannot delete your own account': 'لا يمكنك حذف حسابك',
    payments: 'المدفوعات', 'payment methods': 'طرق الدفع', 'add payment method': 'إضافة طريقة دفع',
    'edit payment method': 'تعديل طريقة الدفع', 'new payment method': 'طريقة دفع جديدة', 'save payment method': 'حفظ طريقة الدفع',
    'delete payment methods': 'حذف طرق الدفع', 'selected payment methods?': 'طريقة دفع مختارة؟',
    'payment method details': 'تفاصيل طريقة الدفع', appearance: 'المظهر',
    'available payment gateways your countries can offer at checkout.': 'بوابات الدفع المتاحة التي يمكن لدولك عرضها عند إتمام الشراء.',
    'a unique machine key the storefront uses (e.g. cod, paymob, fawry, mada, tabby).': 'مفتاح فريد يستخدمه التطبيق (مثل cod, paymob, fawry, mada, tabby).',
    'could not save payment method': 'تعذر حفظ طريقة الدفع',
    transactions: 'العمليات', 'every payment attempt recorded from the storefront, across all countries.': 'كل محاولات الدفع المسجلة من التطبيق، عبر جميع الدول.',
    reference: 'المرجع', method: 'الطريقة', amount: 'المبلغ', methods: ' طرق',
    countries: 'الدول', 'add country': 'إضافة دولة', 'edit country': 'تعديل الدولة', 'new country': 'دولة جديدة',
    'save country': 'حفظ الدولة', 'delete countries': 'حذف الدول', 'selected countries?': 'دول مختارة؟',
    'country code': 'رمز الدولة', 'phone code': 'رمز الهاتف', flag: 'العلم', 'select a currency': 'اختر العملة',
    'country information': 'بيانات الدولة', 'the currency customers are charged in for this country.': 'العملة التي يُدفع بها العملاء في هذه الدولة.',
    'select the payment methods available to customers in this country.': 'اختر طرق الدفع المتاحة للعملاء في هذه الدولة.',
    'no payment methods yet': 'لا توجد طرق دفع بعد', 'add payment methods': 'إضافة طرق دفع',
    'each country has its own currency and the payment methods available to its customers.': 'لكل دولة عملتها الخاصة وطرق الدفع المتاحة لعملائها.',
    'could not save country': 'تعذر حفظ الدولة',
    currencies: 'العملات', 'add currency': 'إضافة عملة', 'edit currency': 'تعديل العملة', 'new currency': 'عملة جديدة',
    'save currency': 'حفظ العملة', 'delete currencies': 'حذف العملات', 'selected currencies?': 'عملات مختارة؟',
    currency: 'العملة', symbol: 'الرمز', base: 'الأساسية', 'base currency': 'العملة الأساسية', 'currency details': 'تفاصيل العملة',
    'rate = how many of this currency equal 1 of your base currency.': 'السعر = كم وحدة من هذه العملة تساوي 1 من عملتك الأساسية.',
    'currencies used by your countries, with the exchange rate against your base currency.': 'العملات المستخدمة في دولك، مع سعر الصرف مقابل عملتك الأساسية.',
    'could not save currency': 'تعذر حفظ العملة',
    'checkout & payments': 'الدفع والمدفوعات', 'enable cash on delivery': 'تفعيل الدفع عند الاستلام', 'default currency': 'العملة الافتراضية',
    'country-based payments': 'مدفوعات حسب الدولة', 'global payment defaults. country-specific payment methods are set per country.': 'الإعدادات الافتراضية للدفع. طرق الدفع الخاصة بكل دولة تُضبط داخل الدولة نفسها.',
    'manage which payment methods are available in each country, and the currency used there.': 'إدارة طرق الدفع المتاحة في كل دولة والعملة المستخدمة فيها.',
    'You are offline. Check your connection and try again.': 'أنت غير متصل بالإنترنت. تحقق من اتصالك وحاول مرة أخرى.',
    'The server is temporarily unreachable. Please try again.': 'الخادم غير متاح مؤقتًا. يرجى المحاولة مرة أخرى.',
    'You are offline. Some features will not work until you reconnect.': 'أنت غير متصل بالإنترنت. بعض الميزات لن تعمل حتى تعيد الاتصال.',
    'The server is temporarily unreachable. We will keep trying.': 'الخادم غير متاح مؤقتًا. سنواصل المحاولة.',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly language = signal<Language>((localStorage.getItem('ecom.language') as Language) || 'en');
  readonly isArabic = signal(this.language() === 'ar');

  constructor() { this.applyDocumentLanguage(); }

  toggle(): void { this.setLanguage(this.language() === 'en' ? 'ar' : 'en'); }

  setLanguage(language: Language): void {
    this.language.set(language);
    this.isArabic.set(language === 'ar');
    localStorage.setItem('ecom.language', language);
    this.applyDocumentLanguage();
  }

  translate(value: string): string {
    const key = value.trim().toLowerCase();
    return translations[this.language()][key] || value;
  }

  localizedValue(obj: any): string {
    if (obj === null || obj === undefined) return '';
    if (typeof obj === 'string') return obj;
    if (typeof obj === 'object' && !Array.isArray(obj)) {
      return obj[this.language()] || obj.en || obj.ar || '';
    }
    return String(obj);
  }

  private applyDocumentLanguage(): void {
    document.documentElement.lang = this.language();
    document.documentElement.dir = this.isArabic() ? 'rtl' : 'ltr';
  }
}
